# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20180103_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.CharField(max_length=1000),
        ),
    ]
