# Generated by Django 2.0.1 on 2018-01-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_album_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to='album_logo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.FileField(upload_to='photo_file'),
        ),
    ]
