# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=500)),
                ('album_logo', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file', models.FileField(upload_to=b'')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Album')),
            ],
        ),
    ]
